//! Cross-module verification against a snapshot and blocks generated by Bitcoin Core 31.1.

use super::test_common as common;
use super::*;
use common::{Fixture, Workspace};
use std::sync::atomic::Ordering;
use usdb_util::ToBtcScriptHash;

#[test]
fn assumeutxo_rpc_preflight_fails_before_reference_io_or_database_open() {
    let work = Workspace::new();
    let mut fixture = Fixture::load();
    let mut options = fixture.options(&work.0);
    options.reference_core = work.0.join("missing-reference.db");
    let root = work.0.join("candidate");
    let _lock = AssumeUtxoWorkspaceLock::acquire(&root, true).unwrap();
    write_report(&root.join("input.json"), &options).unwrap();
    fixture.blocks.clear();
    let error = replay_snapshot(&root, fixture.client(), 103, 2).unwrap_err();
    assert!(error.contains("Replay RPC preflight failed before reference verification"));
    assert!(error.contains("Unknown fixture height"));
    assert!(!root.join("state").exists());
}

#[test]
fn assumeutxo_real_core_import_resume_replay_compare_and_rollback() {
    let work = Workspace::new();
    let fixture = Fixture::load();
    let options = fixture.options(&work.0);
    let root = work.0.join("candidate");
    let _lock = AssumeUtxoWorkspaceLock::acquire(&root, true).unwrap();
    assert!(AssumeUtxoWorkspaceLock::acquire(&root, false).is_err());
    let mut coins = Vec::new();
    let scan = scan_snapshot(&options.snapshot, &options.identity, 7, |batch, _| {
        coins.extend_from_slice(batch);
        Ok(())
    })
    .unwrap();
    assert_eq!(scan.coins, 403);
    assert!(coins.iter().any(|c| c.value == 0 && c.script.is_empty()));
    assert!(coins.iter().any(|c| c.outpoint.vout == 303));
    assert!(coins.iter().any(|c| c.coinbase && c.height == 101));

    // Simulate an interrupted import at an atomic checkpoint, then resume with a different batch size.
    write_report(&root.join("input.json"), &options).unwrap();
    let reference = reference(&options).unwrap();
    let anchor = commit_at(&reference, 101).unwrap();
    {
        let db = BalanceHistoryDB::open(
            Arc::new(config(&root.join("staging"), Network::Regtest)),
            BalanceHistoryDBMode::Normal,
        )
        .unwrap();
        db.begin_assumeutxo_import(&AssumeUtxoImportState {
            identity: options.identity.clone(),
            reference_sha256: options.reference_sha256.clone(),
            base_commit: format::hex(&anchor.block_commit),
            base_delta_root: format::hex(&anchor.balance_delta_root),
            imported_coins: 0,
            complete: false,
        })
        .unwrap();
        db.import_assumeutxo_coins(&coins[..17], 17).unwrap();
        assert!(db.get_query_retention_floors().is_err());
        db.flush_all().unwrap();
    }
    assert!(!root.join("state").exists());
    import_snapshot(&root, &options, 11).unwrap();
    assert_eq!(snapshot_status(&root).unwrap()["published"], true);
    {
        let db = BalanceHistoryDB::open(
            Arc::new(config(&root.join("state"), Network::Regtest)),
            BalanceHistoryDBMode::Normal,
        )
        .unwrap();
        assert_eq!(db.get_query_retention_floors().unwrap(), (101, 102));
        for coin in &coins {
            assert_eq!(
                db.get_utxo(&coin.outpoint).unwrap().unwrap().value,
                coin.value
            );
        }
        let script = coins[0].script.to_btc_script_hash();
        assert_eq!(
            db.get_balance_at_block_height(&script, 101).unwrap().delta,
            0
        );
    }
    replay_snapshot(&root, fixture.client(), 102, 1).unwrap();
    replay_snapshot(&root, fixture.client(), 103, 2).unwrap();
    assert!(compare_snapshot(&root).unwrap().equal);
    {
        let db = BalanceHistoryDB::open(
            Arc::new(config(&root.join("state"), Network::Regtest)),
            BalanceHistoryDBMode::Normal,
        )
        .unwrap();
        assert!(db.rollback_to_block_height(100).is_err());
        assert_eq!(db.get_btc_block_height().unwrap(), 103);
        db.rollback_to_block_height(101).unwrap();
        assert_eq!(db.get_btc_block_height().unwrap(), 101);
        db.flush_all().unwrap();
    }
    replay_snapshot(&root, fixture.client(), 103, 2).unwrap();
    assert!(compare_snapshot(&root).unwrap().equal);
    // Corrupt a live value after comparison: a full projection scan must detect it.
    {
        let db = BalanceHistoryDB::open(
            Arc::new(config(&root.join("state"), Network::Regtest)),
            BalanceHistoryDBMode::Normal,
        )
        .unwrap();
        let coin = coins
            .iter()
            .find(|c| c.coinbase && c.height == 101)
            .unwrap();
        db.update_utxos_async(&vec![], &vec![Arc::new(coin.outpoint)])
            .unwrap();
        db.flush_all().unwrap();
    }
    assert!(!compare_snapshot(&root).unwrap().equal);
    assert_eq!(fixture.fallback_calls.load(Ordering::SeqCst), 0);
}

#[test]
fn assumeutxo_failed_validation_never_publishes_or_accepts_changed_identity() {
    let work = Workspace::new();
    let fixture = Fixture::load();
    let mut options = fixture.options(&work.0);
    options.identity.hash_serialized_3 = "00".repeat(32);
    let root = work.0.join("candidate");
    let _lock = AssumeUtxoWorkspaceLock::acquire(&root, true).unwrap();
    assert!(
        import_snapshot(&root, &options, 17)
            .unwrap_err()
            .contains("commitment mismatch")
    );
    assert!(!root.join("state").exists());
    options.identity.hash_serialized_3 =
        serde_json::from_str::<SnapshotIdentity>(include_str!("fixtures/assumeutxo/identity.json"))
            .unwrap()
            .hash_serialized_3;
    assert!(
        import_snapshot(&root, &options, 17)
            .unwrap_err()
            .contains("differs")
    );
    let mut truncated = fs::read(&options.snapshot).unwrap();
    truncated.pop();
    let corrupt = work.0.join("truncated.dat");
    fs::write(&corrupt, truncated).unwrap();
    assert!(scan_snapshot(&corrupt, &options.identity, 17, |_, _| Ok(())).is_err());
    options.identity.network = Network::Bitcoin;
    assert!(
        scan_snapshot(&options.snapshot, &options.identity, 17, |_, _| Ok(()))
            .unwrap_err()
            .contains("network mismatch")
    );
}

#[test]
fn assumeutxo_missing_prevout_aborts_without_historical_rpc() {
    let work = Workspace::new();
    let fixture = Fixture::load();
    let options = fixture.options(&work.0);
    let root = work.0.join("candidate");
    let _lock = AssumeUtxoWorkspaceLock::acquire(&root, true).unwrap();
    import_snapshot(&root, &options, 100).unwrap();
    {
        let db = BalanceHistoryDB::open(
            Arc::new(config(&root.join("state"), Network::Regtest)),
            BalanceHistoryDBMode::Normal,
        )
        .unwrap();
        let missing = fixture.blocks[102].txdata[1].input[0].previous_output;
        db.update_utxos_async(&vec![], &vec![Arc::new(missing)])
            .unwrap();
        db.flush_all().unwrap();
    }
    assert!(
        replay_snapshot(&root, fixture.client(), 103, 2)
            .unwrap_err()
            .contains("historical RPC fallback is forbidden")
    );
    assert_eq!(fixture.fallback_calls.load(Ordering::SeqCst), 0);
    let db =
        BalanceHistoryDB::open_read_only(Arc::new(config(&root.join("state"), Network::Regtest)))
            .unwrap();
    assert_eq!(db.get_btc_block_height().unwrap(), 101);
}
