use crate::index::{SnapshotSigningKeyFile, SnapshotTrustedKeySet, SnapshotTrustedPublicKey};
use base64::Engine as _;
use ed25519_dalek::SigningKey;
use getrandom::fill as getrandom_fill;
use std::path::{Path, PathBuf};

/// On-disk public-key export for one snapshot signer.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize, PartialEq, Eq)]
pub struct SnapshotPublicKeyFile {
    /// Logical signer identifier.
    pub key_id: String,
    /// Ed25519 public key encoded as base64(raw 32-byte bytes).
    pub public_key_base64: String,
}

/// Output paths generated by `snapshot-keygen`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SnapshotKeygenOutput {
    pub signing_key_file: PathBuf,
    pub public_key_file: PathBuf,
    pub trusted_keys_file: PathBuf,
}

/// Generates one snapshot signing key plus matching public-key exports.
pub fn generate_snapshot_key_files(
    out_dir: &Path,
    key_id: &str,
    force: bool,
) -> Result<SnapshotKeygenOutput, String> {
    if key_id.trim().is_empty() {
        let msg = "Snapshot signer key_id cannot be empty".to_string();
        error!("{}", msg);
        return Err(msg);
    }
    std::fs::create_dir_all(out_dir).map_err(|e| {
        let msg = format!(
            "Failed to create snapshot key output directory {}: {}",
            out_dir.display(),
            e
        );
        error!("{}", msg);
        msg
    })?;

    let signing_key_path = out_dir.join(format!("{}.signing-key.json", key_id));
    let public_key_path = out_dir.join(format!("{}.public-key.json", key_id));
    let trusted_keys_path = out_dir.join(format!("{}.trusted-keys.json", key_id));
    for path in [&signing_key_path, &public_key_path, &trusted_keys_path] {
        if path.exists() && !force {
            let msg = format!(
                "Refusing to overwrite existing snapshot key file {}; rerun with force enabled",
                path.display()
            );
            error!("{}", msg);
            return Err(msg);
        }
    }

    let mut seed = [0u8; 32];
    getrandom_fill(&mut seed).map_err(|e| {
        let msg = format!(
            "Failed to generate random seed for snapshot signer {}: {}",
            key_id, e
        );
        error!("{}", msg);
        msg
    })?;
    let signing_key = SigningKey::from_bytes(&seed);
    let public_key = signing_key.verifying_key();

    let signing_key_file = SnapshotSigningKeyFile {
        key_id: key_id.to_string(),
        secret_key_base64: base64::engine::general_purpose::STANDARD.encode(signing_key.to_bytes()),
    };
    let public_key_file = SnapshotPublicKeyFile {
        key_id: key_id.to_string(),
        public_key_base64: base64::engine::general_purpose::STANDARD.encode(public_key.to_bytes()),
    };
    let trusted_keys_file = SnapshotTrustedKeySet {
        keys: vec![SnapshotTrustedPublicKey {
            key_id: key_id.to_string(),
            public_key_base64: public_key_file.public_key_base64.clone(),
        }],
    };

    write_json_file(&signing_key_path, &signing_key_file)?;
    write_json_file(&public_key_path, &public_key_file)?;
    write_json_file(&trusted_keys_path, &trusted_keys_file)?;
    set_private_file_permissions(&signing_key_path)?;

    Ok(SnapshotKeygenOutput {
        signing_key_file: signing_key_path,
        public_key_file: public_key_path,
        trusted_keys_file: trusted_keys_path,
    })
}

fn write_json_file<T: serde::Serialize>(path: &Path, value: &T) -> Result<(), String> {
    let data = serde_json::to_vec_pretty(value).map_err(|e| {
        let msg = format!("Failed to serialize JSON file {}: {}", path.display(), e);
        error!("{}", msg);
        msg
    })?;
    std::fs::write(path, data).map_err(|e| {
        let msg = format!("Failed to write JSON file {}: {}", path.display(), e);
        error!("{}", msg);
        msg
    })
}

#[cfg(unix)]
fn set_private_file_permissions(path: &Path) -> Result<(), String> {
    use std::os::unix::fs::PermissionsExt;

    let permissions = std::fs::Permissions::from_mode(0o600);
    std::fs::set_permissions(path, permissions).map_err(|e| {
        let msg = format!(
            "Failed to set private permissions on snapshot signing key {}: {}",
            path.display(),
            e
        );
        error!("{}", msg);
        msg
    })
}

#[cfg(not(unix))]
fn set_private_file_permissions(_path: &Path) -> Result<(), String> {
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use ed25519_dalek::{Signer, Verifier, VerifyingKey};
    use std::time::{SystemTime, UNIX_EPOCH};

    fn temp_root(tag: &str) -> PathBuf {
        let nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        let root = std::env::temp_dir().join(format!("snapshot_keygen_{}_{}", tag, nanos));
        std::fs::create_dir_all(&root).unwrap();
        root
    }

    #[test]
    fn test_generate_snapshot_key_files_round_trip() {
        let root = temp_root("round_trip");
        let output = generate_snapshot_key_files(&root, "snapshot-signer-1", false).unwrap();

        assert!(output.signing_key_file.exists());
        assert!(output.public_key_file.exists());
        assert!(output.trusted_keys_file.exists());

        let signing_key_file: SnapshotSigningKeyFile =
            serde_json::from_slice(&std::fs::read(&output.signing_key_file).unwrap()).unwrap();
        let public_key_file: SnapshotPublicKeyFile =
            serde_json::from_slice(&std::fs::read(&output.public_key_file).unwrap()).unwrap();
        let trusted_keys: SnapshotTrustedKeySet =
            serde_json::from_slice(&std::fs::read(&output.trusted_keys_file).unwrap()).unwrap();

        assert_eq!(signing_key_file.key_id, "snapshot-signer-1");
        assert_eq!(public_key_file.key_id, "snapshot-signer-1");
        assert_eq!(trusted_keys.keys.len(), 1);
        assert_eq!(trusted_keys.keys[0].key_id, "snapshot-signer-1");
        assert_eq!(
            trusted_keys.keys[0].public_key_base64,
            public_key_file.public_key_base64
        );

        let secret_raw = base64::engine::general_purpose::STANDARD
            .decode(signing_key_file.secret_key_base64.as_bytes())
            .unwrap();
        let secret_bytes: [u8; 32] = secret_raw.as_slice().try_into().unwrap();
        let signing_key = SigningKey::from_bytes(&secret_bytes);
        let public_raw = base64::engine::general_purpose::STANDARD
            .decode(public_key_file.public_key_base64.as_bytes())
            .unwrap();
        let public_bytes: [u8; 32] = public_raw.as_slice().try_into().unwrap();
        let verifying_key = VerifyingKey::from_bytes(&public_bytes).unwrap();

        let message = b"snapshot-keygen-test";
        let signature = signing_key.sign(message);
        verifying_key.verify(message, &signature).unwrap();
    }

    #[test]
    fn test_generate_snapshot_key_files_rejects_overwrite_without_force() {
        let root = temp_root("overwrite");
        generate_snapshot_key_files(&root, "snapshot-signer-1", false).unwrap();
        let err = generate_snapshot_key_files(&root, "snapshot-signer-1", false).unwrap_err();
        assert!(err.contains("Refusing to overwrite"));
    }
}
