services:
  snapshot-loader:
    labels:
      org.usdb.network-bundle: usdb-testnet-v1
  balance-history:
    labels:
      org.usdb.network-bundle: usdb-testnet-v1
  usdb-indexer:
    labels:
      org.usdb.network-bundle: usdb-testnet-v1
  paired-checkpoint-recovery:
    labels:
      org.usdb.network-bundle: usdb-testnet-v1
  usdb-chain-init:
    labels:
      org.usdb.network-bundle: usdb-testnet-v1
  usdb-chain:
    labels:
      org.usdb.network-bundle: usdb-testnet-v1
  usdb-control-plane:
    labels:
      org.usdb.network-bundle: usdb-testnet-v1
