#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export SIM_VALIDATOR_SAMPLE_ENABLED="${SIM_VALIDATOR_SAMPLE_ENABLED:-1}"
export SIM_VALIDATOR_SAMPLE_INTERVAL_BLOCKS="${SIM_VALIDATOR_SAMPLE_INTERVAL_BLOCKS:-6}"
export SIM_VALIDATOR_SAMPLE_SIZE="${SIM_VALIDATOR_SAMPLE_SIZE:-1}"
export SIM_VALIDATOR_SAMPLE_MIN_HEAD_ADVANCE="${SIM_VALIDATOR_SAMPLE_MIN_HEAD_ADVANCE:-2}"

exec bash "${SCRIPT_DIR}/regtest_world_sim.sh" "$@"
