#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DETERMINISM_SCRIPT="${SCRIPT_DIR}/regtest_world_sim_determinism.sh"
WORLD_SIM_REORG_SCRIPT="${SCRIPT_DIR}/regtest_world_sim_reorg.sh"

WORK_DIR="${WORK_DIR:-/tmp/usdb-world-determinism-reorg}"
SIM_SEED="${SIM_SEED:-20260318}"
SIM_BLOCKS="${SIM_BLOCKS:-80}"
AGENT_COUNT="${AGENT_COUNT:-6}"
SIM_FAIL_FAST="${SIM_FAIL_FAST:-1}"
SIM_REPORT_FLUSH_EVERY="${SIM_REPORT_FLUSH_EVERY:-1}"

SIM_POLICY_MODE="${SIM_POLICY_MODE:-scripted}"
SIM_SCRIPTED_CYCLE="${SIM_SCRIPTED_CYCLE:-mint,send_balance,transfer,remint,spend_balance,noop}"
SIM_REORG_INTERVAL_BLOCKS="${SIM_REORG_INTERVAL_BLOCKS:-20}"
SIM_REORG_DEPTH="${SIM_REORG_DEPTH:-3}"
SIM_REORG_MAX_EVENTS="${SIM_REORG_MAX_EVENTS:-2}"
SIM_GLOBAL_CROSS_CHECK_INTERVAL_BLOCKS="${SIM_GLOBAL_CROSS_CHECK_INTERVAL_BLOCKS:-5}"
SIM_AGENT_SELF_CHECK_INTERVAL_BLOCKS="${SIM_AGENT_SELF_CHECK_INTERVAL_BLOCKS:-1}"

exec env \
  WORK_DIR="${WORK_DIR}" \
  WORLD_SIM_SCRIPT="${WORLD_SIM_REORG_SCRIPT}" \
  SIM_SEED="${SIM_SEED}" \
  SIM_BLOCKS="${SIM_BLOCKS}" \
  AGENT_COUNT="${AGENT_COUNT}" \
  SIM_FAIL_FAST="${SIM_FAIL_FAST}" \
  SIM_REPORT_FLUSH_EVERY="${SIM_REPORT_FLUSH_EVERY}" \
  SIM_POLICY_MODE="${SIM_POLICY_MODE}" \
  SIM_SCRIPTED_CYCLE="${SIM_SCRIPTED_CYCLE}" \
  SIM_REORG_INTERVAL_BLOCKS="${SIM_REORG_INTERVAL_BLOCKS}" \
  SIM_REORG_DEPTH="${SIM_REORG_DEPTH}" \
  SIM_REORG_MAX_EVENTS="${SIM_REORG_MAX_EVENTS}" \
  SIM_GLOBAL_CROSS_CHECK_INTERVAL_BLOCKS="${SIM_GLOBAL_CROSS_CHECK_INTERVAL_BLOCKS}" \
  SIM_AGENT_SELF_CHECK_INTERVAL_BLOCKS="${SIM_AGENT_SELF_CHECK_INTERVAL_BLOCKS}" \
  bash "${DETERMINISM_SCRIPT}"
