#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export SIM_VALIDATOR_SAMPLE_ENABLED="${SIM_VALIDATOR_SAMPLE_ENABLED:-1}"
export SIM_VALIDATOR_SAMPLE_MODE="${SIM_VALIDATOR_SAMPLE_MODE:-candidate_set}"
export SIM_VALIDATOR_SAMPLE_TAMPER_ENABLED="${SIM_VALIDATOR_SAMPLE_TAMPER_ENABLED:-1}"
export SIM_VALIDATOR_SAMPLE_INTERVAL_BLOCKS="${SIM_VALIDATOR_SAMPLE_INTERVAL_BLOCKS:-7}"
export SIM_VALIDATOR_SAMPLE_SIZE="${SIM_VALIDATOR_SAMPLE_SIZE:-3}"
export SIM_VALIDATOR_SAMPLE_MIN_HEAD_ADVANCE="${SIM_VALIDATOR_SAMPLE_MIN_HEAD_ADVANCE:-2}"
export SIM_REORG_INTERVAL_BLOCKS="${SIM_REORG_INTERVAL_BLOCKS:-8}"
export SIM_REORG_DEPTH="${SIM_REORG_DEPTH:-2}"
export SIM_REORG_MAX_EVENTS="${SIM_REORG_MAX_EVENTS:-1}"

exec bash "${SCRIPT_DIR}/regtest_world_sim.sh" "$@"
