#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RUN_LIVE_SCRIPT="${SCRIPT_DIR}/run_live.sh"

# Base workspace for this long-running reorg soak session.
WORK_DIR="${WORK_DIR:-/tmp/usdb-world-live-reorg}"
# Reuse run_live reset semantics.
RESET_WORK_DIR="${RESET_WORK_DIR:-1}"
RESET_WORK_DIR_FORCE="${RESET_WORK_DIR_FORCE:-0}"

# Bitcoin Core binaries directory (contains bitcoind and bitcoin-cli).
BITCOIN_BIN_DIR="${BITCOIN_BIN_DIR:-/home/bucky/btc/bitcoin-28.1/bin}"
# ord executable used for mint/transfer transaction construction.
ORD_BIN="${ORD_BIN:-/home/bucky/ord/target/release/ord}"

# RPC and p2p ports for isolated local services.
BTC_RPC_PORT="${BTC_RPC_PORT:-28232}"
BTC_P2P_PORT="${BTC_P2P_PORT:-28233}"
BH_RPC_PORT="${BH_RPC_PORT:-28210}"
USDB_RPC_PORT="${USDB_RPC_PORT:-28220}"
ORD_SERVER_PORT="${ORD_SERVER_PORT:-28230}"

# Long-run soak defaults.
AGENT_COUNT="${AGENT_COUNT:-120}"
PREMINE_BLOCKS="${PREMINE_BLOCKS:-220}"
FUND_AGENT_AMOUNT_BTC="${FUND_AGENT_AMOUNT_BTC:-8.0}"
FUND_CONFIRM_BLOCKS="${FUND_CONFIRM_BLOCKS:-2}"
SYNC_TIMEOUT_SEC="${SYNC_TIMEOUT_SEC:-1800}"

SIM_BLOCKS="${SIM_BLOCKS:-2500}"
SIM_SEED="${SIM_SEED:-20260318}"
SIM_FEE_RATE="${SIM_FEE_RATE:-1}"
SIM_MAX_ACTIONS_PER_BLOCK="${SIM_MAX_ACTIONS_PER_BLOCK:-6}"
SIM_SLEEP_MS_BETWEEN_BLOCKS="${SIM_SLEEP_MS_BETWEEN_BLOCKS:-80}"
SIM_FAIL_FAST="${SIM_FAIL_FAST:-0}"

SIM_INITIAL_ACTIVE_AGENTS="${SIM_INITIAL_ACTIVE_AGENTS:-24}"
SIM_AGENT_GROWTH_INTERVAL_BLOCKS="${SIM_AGENT_GROWTH_INTERVAL_BLOCKS:-25}"
SIM_AGENT_GROWTH_STEP="${SIM_AGENT_GROWTH_STEP:-3}"

SIM_POLICY_MODE="${SIM_POLICY_MODE:-adaptive}"
SIM_SCRIPTED_CYCLE="${SIM_SCRIPTED_CYCLE:-mint,send_balance,transfer,remint,spend_balance,noop}"

SIM_MINT_PROBABILITY="${SIM_MINT_PROBABILITY:-0.24}"
SIM_INVALID_MINT_PROBABILITY="${SIM_INVALID_MINT_PROBABILITY:-0.03}"
SIM_TRANSFER_PROBABILITY="${SIM_TRANSFER_PROBABILITY:-0.22}"
SIM_REMINT_PROBABILITY="${SIM_REMINT_PROBABILITY:-0.15}"
SIM_SEND_PROBABILITY="${SIM_SEND_PROBABILITY:-0.24}"
SIM_SPEND_PROBABILITY="${SIM_SPEND_PROBABILITY:-0.12}"

SIM_REPORT_ENABLED="${SIM_REPORT_ENABLED:-1}"
SIM_REPORT_FILE="${SIM_REPORT_FILE:-${WORK_DIR}/world-sim-live-reorg.jsonl}"
SIM_REPORT_FLUSH_EVERY="${SIM_REPORT_FLUSH_EVERY:-1}"
SIM_GLOBAL_CROSS_CHECK_ENABLED="${SIM_GLOBAL_CROSS_CHECK_ENABLED:-1}"
SIM_GLOBAL_CROSS_CHECK_INTERVAL_BLOCKS="${SIM_GLOBAL_CROSS_CHECK_INTERVAL_BLOCKS:-25}"
SIM_GLOBAL_CROSS_CHECK_LEADERBOARD_TOP_N="${SIM_GLOBAL_CROSS_CHECK_LEADERBOARD_TOP_N:-20}"
SIM_GLOBAL_CROSS_CHECK_OWNER_SAMPLE_SIZE="${SIM_GLOBAL_CROSS_CHECK_OWNER_SAMPLE_SIZE:-16}"
SIM_AGENT_SELF_CHECK_ENABLED="${SIM_AGENT_SELF_CHECK_ENABLED:-1}"
SIM_AGENT_SELF_CHECK_INTERVAL_BLOCKS="${SIM_AGENT_SELF_CHECK_INTERVAL_BLOCKS:-5}"
SIM_AGENT_SELF_CHECK_SAMPLE_SIZE="${SIM_AGENT_SELF_CHECK_SAMPLE_SIZE:-0}"

# Deterministic reorg injection defaults for soak coverage.
SIM_REORG_INTERVAL_BLOCKS="${SIM_REORG_INTERVAL_BLOCKS:-180}"
SIM_REORG_DEPTH="${SIM_REORG_DEPTH:-3}"
SIM_REORG_MAX_EVENTS="${SIM_REORG_MAX_EVENTS:-8}"

DIAG_TAIL_LINES="${DIAG_TAIL_LINES:-200}"

log() {
  echo "[run-live-reorg] $*"
}

main() {
  if [[ ! -f "${RUN_LIVE_SCRIPT}" ]]; then
    echo "Missing script: ${RUN_LIVE_SCRIPT}" >&2
    exit 1
  fi

  log "Starting live reorg soak with AGENT_COUNT=${AGENT_COUNT}, SIM_BLOCKS=${SIM_BLOCKS}, reorg_interval=${SIM_REORG_INTERVAL_BLOCKS}, reorg_depth=${SIM_REORG_DEPTH}, reorg_max_events=${SIM_REORG_MAX_EVENTS}"
  log "USDB RPC endpoint: http://127.0.0.1:${USDB_RPC_PORT}"
  log "Report file: ${SIM_REPORT_FILE}"

  exec env \
    WORK_DIR="${WORK_DIR}" \
    RESET_WORK_DIR="${RESET_WORK_DIR}" \
    RESET_WORK_DIR_FORCE="${RESET_WORK_DIR_FORCE}" \
    BITCOIN_BIN_DIR="${BITCOIN_BIN_DIR}" \
    ORD_BIN="${ORD_BIN}" \
    BTC_RPC_PORT="${BTC_RPC_PORT}" \
    BTC_P2P_PORT="${BTC_P2P_PORT}" \
    BH_RPC_PORT="${BH_RPC_PORT}" \
    USDB_RPC_PORT="${USDB_RPC_PORT}" \
    ORD_SERVER_PORT="${ORD_SERVER_PORT}" \
    AGENT_COUNT="${AGENT_COUNT}" \
    PREMINE_BLOCKS="${PREMINE_BLOCKS}" \
    FUND_AGENT_AMOUNT_BTC="${FUND_AGENT_AMOUNT_BTC}" \
    FUND_CONFIRM_BLOCKS="${FUND_CONFIRM_BLOCKS}" \
    SYNC_TIMEOUT_SEC="${SYNC_TIMEOUT_SEC}" \
    SIM_BLOCKS="${SIM_BLOCKS}" \
    SIM_SEED="${SIM_SEED}" \
    SIM_FEE_RATE="${SIM_FEE_RATE}" \
    SIM_MAX_ACTIONS_PER_BLOCK="${SIM_MAX_ACTIONS_PER_BLOCK}" \
    SIM_SLEEP_MS_BETWEEN_BLOCKS="${SIM_SLEEP_MS_BETWEEN_BLOCKS}" \
    SIM_FAIL_FAST="${SIM_FAIL_FAST}" \
    SIM_INITIAL_ACTIVE_AGENTS="${SIM_INITIAL_ACTIVE_AGENTS}" \
    SIM_AGENT_GROWTH_INTERVAL_BLOCKS="${SIM_AGENT_GROWTH_INTERVAL_BLOCKS}" \
    SIM_AGENT_GROWTH_STEP="${SIM_AGENT_GROWTH_STEP}" \
    SIM_POLICY_MODE="${SIM_POLICY_MODE}" \
    SIM_SCRIPTED_CYCLE="${SIM_SCRIPTED_CYCLE}" \
    SIM_MINT_PROBABILITY="${SIM_MINT_PROBABILITY}" \
    SIM_INVALID_MINT_PROBABILITY="${SIM_INVALID_MINT_PROBABILITY}" \
    SIM_TRANSFER_PROBABILITY="${SIM_TRANSFER_PROBABILITY}" \
    SIM_REMINT_PROBABILITY="${SIM_REMINT_PROBABILITY}" \
    SIM_SEND_PROBABILITY="${SIM_SEND_PROBABILITY}" \
    SIM_SPEND_PROBABILITY="${SIM_SPEND_PROBABILITY}" \
    SIM_REPORT_ENABLED="${SIM_REPORT_ENABLED}" \
    SIM_REPORT_FILE="${SIM_REPORT_FILE}" \
    SIM_REPORT_FLUSH_EVERY="${SIM_REPORT_FLUSH_EVERY}" \
    SIM_GLOBAL_CROSS_CHECK_ENABLED="${SIM_GLOBAL_CROSS_CHECK_ENABLED}" \
    SIM_GLOBAL_CROSS_CHECK_INTERVAL_BLOCKS="${SIM_GLOBAL_CROSS_CHECK_INTERVAL_BLOCKS}" \
    SIM_GLOBAL_CROSS_CHECK_LEADERBOARD_TOP_N="${SIM_GLOBAL_CROSS_CHECK_LEADERBOARD_TOP_N}" \
    SIM_GLOBAL_CROSS_CHECK_OWNER_SAMPLE_SIZE="${SIM_GLOBAL_CROSS_CHECK_OWNER_SAMPLE_SIZE}" \
    SIM_AGENT_SELF_CHECK_ENABLED="${SIM_AGENT_SELF_CHECK_ENABLED}" \
    SIM_AGENT_SELF_CHECK_INTERVAL_BLOCKS="${SIM_AGENT_SELF_CHECK_INTERVAL_BLOCKS}" \
    SIM_AGENT_SELF_CHECK_SAMPLE_SIZE="${SIM_AGENT_SELF_CHECK_SAMPLE_SIZE}" \
    SIM_REORG_INTERVAL_BLOCKS="${SIM_REORG_INTERVAL_BLOCKS}" \
    SIM_REORG_DEPTH="${SIM_REORG_DEPTH}" \
    SIM_REORG_MAX_EVENTS="${SIM_REORG_MAX_EVENTS}" \
    DIAG_TAIL_LINES="${DIAG_TAIL_LINES}" \
    bash "${RUN_LIVE_SCRIPT}"
}

main "$@"
